server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/
    username: root
    password: admin123

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.JBossAppServerJtaPlatform