server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/the_sun_hospital
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      format_sql: true
      hibernate.transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.JBossAppServerJtaPlatform
  jwt:
    secret: "QUcjdvn1oZK4h4feKPgAAedV0XZrwZY1P7dKS5JV0R8="
